version: '3.7'
services:
  tabarnotte:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html:Z
  node:
    image: node
    working_dir: /home/node/app
    volumes:
      - ./websocket:/home/node/app:Z
    ports:
      - "8080:8080"
    command: "server.js"
